### PR TITLE
spatially localized RPC

### PR DESCRIPTION
**Pull request by ceriottm**
Spatially Localized Contraction. 

* gives possibility of only passing a subset of the atoms to the driver
* examples that use this to do RPC for a subsystem

### CODE REVIEW

**Comment by ceriottm** [comment]
The example zundel-systempart does not conserve *at all*

**Comment by ceriottm** [comment]
Though this had been merged already. Mariana do you mind merging in master and closing merging this PR for good?

**Comment by mahrossi** [comment]
No problem, go ahead. Nothing has changed since the last merge. If there is
anything new we can open a new branch.

**Comment by ceriottm** [comment]
OK merging this now. Hope does not trigger anything unexpected. @mahrossi  would be nice if you could add a section to the website (basically the gh-pages branch on the stable i-pi repo)  mentioning the new paper and this feature.

**Pull request merged**
