### PR TITLE
Instanton 

### PR DESCRIPTION
**Pull request by litman90**
The code is working and doesn't break any other part of the code.
It deals with instanton rate calculation and tunneling splitting.
Examples and auxiliary scripts are also provided, namely, interpolation and postprocessing.

However, there are two major things that can/should be improved in the near future:
  - in the instanton calculation, we compute only half of the ring polymer(RP), 
    so all the contraction/expansion routines cannot be used in a straightforward way (for example initialization and communicate a contracted RP to the client)
  - In some extent, this branch has overlap with GEOP and PHONON because those branches 
    do not consider nbeads>1. It is not such few lines, it is implicitly hardcoded.

Probably when Venkat is here in Berlin, we could discuss which is the best solution to implement.

### CODE REVIEW

**Comment by mahrossi** [comment]
Just as a heads-up, we have discussed this before, and I had already signaled to Michele these major issues. Happy to have a call with all people involved in order to choose the best implementation strategy to continue from here. The implementation as is works as a charm in order to calculate instanton-related properties, so it is certainly a valid addition to i-PI. Other than that, we are waiting for you @venkatkapil24 :D

**Comment by venkatkapil24** [comment]
Sure i am happy to pitch in

**Comment by ceriottm** [comment]
Did you guys add regtests for the instanton stuff? I think that other than that we're ready to merge

**Comment by mahrossi** [comment]
They are in the examples folder, since last time I checked.
We can add to regression tests too.

**Pull request merged**
